import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {normalizeContentRecord,buildGenerationManifest,runContentQc,buildAssetSourceRevision} from '../src/content-model.mjs';
import {assessProduction,changeToken} from '../src/production-assistant.mjs';
import {resolveFastVisualPlan,informationSnapshot} from '../src/fast-visual-plan.mjs';
import {createProductionBatch,createProductionBatchFromSelection,selectBatchCandidates,resolveProductionBatch,planBatchImports,matchBatchFilename,batchImagePrompt,batchPostStamp,reconcileProductionBatch} from '../src/batch-production.mjs';
import {assetSemanticKey,sessionSignature} from '../src/production-core.mjs';
const recipes=JSON.parse(await readFile(new URL('../data/recipes.json',import.meta.url))),v4=JSON.parse(await readFile(new URL('../data/v4-production-batch-01.json',import.meta.url)));
const recipe=normalizeContentRecord(recipes.recipes.find(r=>r.Content_ID==='EN-NEW-009'));
const types=v4.records.map(normalizeContentRecord);
const row=(c,i)=>({sheetId:i%2?433728120:2026091901,contentId:c.contentId,title:c.title,contentType:c.contentType,content:c,duplicateStatus:'UNIQUE',lifecycleStatus:'DRAFT',assessment:assessProduction(c)});
const readyRows=[row(recipe,0),...types.map((c,i)=>row(c,i+1))].filter(r=>r.assessment.ready&&r.assessment.risk.tier==='LOW');
function fixtures(batch,rows,completePosts=5){let r=resolveProductionBatch(batch,rows),imagesByKey=new Map(),assetsByKey=new Map(),visualByKey=new Map();for(const p of r.posts.slice(0,completePosts)){const images={},assets={};for(const e of p.entries){const image={revision:`image-${p.postNumber}-${e.slotId}`,semanticKey:e.semanticKey,qc:{status:'PASS'}};images[e.slotId]=image;imagesByKey.set(`${e.postKey}:image:${e.slotId}`,image);}for(const a of p.plan){const value={qc_status:'PASS',semanticKey:assetSemanticKey(a),sourceRevision:buildAssetSourceRevision(a,images),stale:false,updatedAt:1};assets[a.asset_id]=value;assetsByKey.set(`${p.sheetId}:${p.contentId}:asset:${a.asset_id}`,value);}visualByKey.set(`${p.sheetId}:${p.contentId}`,changeToken(sessionSignature(p.content,p.manifest,images,assets)));}return {imagesByKey,assetsByKey,visualByKey};}
test('six legacy method steps resolve from nine source images to five without losing instructions or quantities',()=>{const before=JSON.stringify(recipe),fast=resolveFastVisualPlan(recipe);assert.equal(buildGenerationManifest(recipe).entries.length,9);assert.equal(buildGenerationManifest(fast).entries.length,5);assert.deepEqual(informationSnapshot(fast),informationSnapshot(recipe));assert.equal(JSON.stringify(recipe),before);assert.deepEqual(fast.fastVisualPlan.informationLost,[]);assert.equal(fast.fastVisualPlan.methodMapping.length,6);assert.equal(new Set(fast.fastVisualPlan.methodMapping.map(m=>m.photoSlot)).size,2);assert.equal(runContentQc(fast).failures.length,0);assert.deepEqual(resolveFastVisualPlan(fast),fast);});
test('an independent shaping stage earns an additional source photo rather than squeezing all methods into two images',()=>{const source=structuredClone(recipe),m=source.resolvedAssetPlan.find(a=>a.asset_type==='METHOD');m.generation_inputs[3].overlay_text='整形\n按来源将面团整形。';m.generation_inputs[3].image_prompt='Shaping the source dough';assert.equal(buildGenerationManifest(resolveFastVisualPlan(source)).entries.length,6);});
test('V4 Selection Guide, Mistake/Fix and Tips retain all source information and coverage',()=>{for(const source of types.filter(c=>['SELECTION_GUIDE','MISTAKE_FIX','REFERENCE_GUIDE'].includes(c.contentType))){const fast=resolveFastVisualPlan(source);assert.deepEqual(informationSnapshot(fast),informationSnapshot(source));assert.equal(runContentQc(fast).failures.length,0);assert.ok(buildGenerationManifest(fast).entries.length<=6);for(const a of fast.resolvedAssetPlan){for(const id of a.source_input_ids||[])assert.ok(buildGenerationManifest(fast).entries.some(e=>e.slotId===id));}}});
test('batch selection excludes held/rework duplicates, published, risky, weak and incomplete records; does not pad',()=>{const good=readyRows[0],rows=[good,{...good,contentId:'dup',duplicateStatus:'HOLD_DUPLICATE'},{...good,contentId:'possible',duplicateStatus:'REWORK'},{...good,contentId:'posted',lifecycleStatus:'POSTED'},{...good,contentId:'recorded',publicationRecorded:true},{...good,contentId:'risk',assessment:{...good.assessment,risk:{tier:'MEDIUM'}}},{...good,contentId:'weak',assessment:{...good.assessment,ready:false,recommendation:'IMPROVE'}}];assert.deepEqual(selectBatchCandidates(rows,20),[good]);assert.equal(createProductionBatch(rows,20).posts.length,1);});
test('batch favours type variety and returns deterministic strong candidates',()=>{const selected=selectBatchCandidates(readyRows,5);assert.equal(selected.length,5);assert.ok(new Set(selected.map(r=>r.contentType)).size>=3);assert.deepEqual(selectBatchCandidates(readyRows,5).map(r=>r.contentId),selected.map(r=>r.contentId));});
test('5-post queue resolves deterministic batch/post/slot filenames and exact-one-image commands with identity reset',()=>{const b=createProductionBatch(readyRows,5),r=resolveProductionBatch(b,readyRows);assert.equal(r.posts.length,5);assert.ok(r.totalImages>=15&&r.totalImages<=30);assert.equal(r.imagesReady,0);assert.ok(r.entries.every(e=>/^B01_P\d{2}_\d{2}_/.test(e.batchFilename)));const prompt=batchImagePrompt(b,r);assert.match(prompt,/exactly ONE image per response/);assert.match(prompt,/RESET VISUAL IDENTITY/);assert.match(prompt,/FIX:/);assert.match(prompt,/R = regenerate/);assert.equal((prompt.match(/RESET VISUAL IDENTITY — POST/g)||[]).length,5);assert.match(batchImagePrompt(b,r,{entry:r.next}),new RegExp(r.next.batchFilename.replace('.','\\.')));});
test('20-post planning returns eligible source records only and reports accurate image totals',()=>{const rows=Array.from({length:24},(_,i)=>{const c={...readyRows[i%readyRows.length].content,contentId:`QA-${i}`,title:`QA source ${i}`};return row(c,i);}),b=createProductionBatch(rows,20),r=resolveProductionBatch(b,rows);assert.equal(r.posts.length,20);assert.equal(new Set(r.posts.map(p=>`${p.sheetId}:${p.contentId}`)).size,20);assert.equal(r.totalImages,r.posts.reduce((n,p)=>n+p.entries.length,0));assert.ok(r.totalImages/r.posts.length<=6);});
test('batch import maps reversed downloaded filenames, refuses conflicts and isolates duplicate target exceptions',()=>{const b=createProductionBatch(readyRows,5),r=resolveProductionBatch(b,readyRows),e=r.entries[0],files=r.entries.slice().reverse().map(e=>({name:e.batchFilename}));assert.equal(planBatchImports(files,r).matched.length,r.totalImages);assert.equal(matchBatchFilename(`ChatGPT ${e.batchFilename}`,r)?.slotId,e.slotId);assert.equal(matchBatchFilename(e.batchFilename.replace('B01','B02'),r),null);assert.equal(matchBatchFilename(`B02_P01_01_X ${e.batchFilename}`,r),null);assert.equal(matchBatchFilename(e.batchFilename.replace(e.slotId.toUpperCase(),'UNKNOWN'),r),null);assert.equal(matchBatchFilename(e.expectedFilename,r),null);const result=planBatchImports([files[0],files[0],files[1]],r);assert.equal(result.matched.length,1);assert.equal(result.unmatched.length,2);});
test('partial batch builds and downloads independently, resume selects next missing post image',()=>{const b=createProductionBatch(readyRows,5),stores=fixtures(b,readyRows,2),r=resolveProductionBatch(b,readyRows,stores);assert.equal(r.builtCount,2);assert.equal(r.downloadReady,2);assert.equal(r.next.postNumber,3);assert.equal(r.imagesReady,r.posts.slice(0,2).reduce((n,p)=>n+p.entries.length,0));const resumed=resolveProductionBatch(JSON.parse(JSON.stringify(b)),readyRows,stores);assert.deepEqual(resumed.next,r.next);stores.assetsByKey.clear();const pending=resolveProductionBatch(b,readyRows,stores);assert.equal(pending.readyToBuild,2);assert.equal(pending.downloadReady,0);});
test('stale image revisions and changed source plans block only their post export',()=>{const b=createProductionBatch(readyRows,5),stores=fixtures(b,readyRows,2),initial=resolveProductionBatch(b,readyRows,stores),e=initial.entries[0],image=stores.imagesByKey.get(`${e.postKey}:image:${e.slotId}`);image.revision='replacement';let r=resolveProductionBatch(b,readyRows,stores);assert.equal(r.posts[0].reviewed,false);assert.equal(r.posts[0].built,false);assert.equal(r.downloadReady,1);const altered=readyRows.map(row=>row.contentId===b.posts[1].contentId?{...row,assessment:{...row.assessment,content:{...row.assessment.content,caption:'Source presentation changed'}}}:row);r=resolveProductionBatch(b,altered,stores);assert.equal(r.posts[1].valid,false);assert.equal(r.posts[1].reviewed,false);assert.notEqual(batchPostStamp(altered.find(row=>row.contentId===b.posts[1].contentId)),b.posts[1].stamp);});
test('a FIX or REGENERATE decision vetoes batch export even when visual signature remains present',()=>{const b=createProductionBatch(readyRows,5),stores=fixtures(b,readyRows,1),r=resolveProductionBatch(b,readyRows,stores),e=r.entries[0],image=stores.imagesByKey.get(`${e.postKey}:image:${e.slotId}`);stores.reviewsByKey=new Map([[`${e.postKey}:image-review:${e.slotId}`,{status:'FIX IMAGE',imageRevision:image.revision}]]);assert.equal(resolveProductionBatch(b,readyRows,stores).downloadReady,0);});

test('visual signatures do not depend on IndexedDB asset insertion order',()=>{const c=assessProduction(recipe).content,m=buildGenerationManifest(c),a={a:{semanticKey:'a',updatedAt:1},b:{semanticKey:'b',updatedAt:2}};assert.equal(sessionSignature(c,m,{},a),sessionSignature(c,m,{},Object.fromEntries(Object.entries(a).reverse())));});

test('missing Page profile normalizes identically for individual and batch visual approval',()=>{const c=assessProduction(recipe).content,m=buildGenerationManifest(c);assert.equal(sessionSignature(c,m,{},{}),sessionSignature({...c,pageProfile:null},m,{},{}));});

test('resumed batch prompts omit imported images and preserve post-specific identity resets',()=>{const b=createProductionBatch(readyRows,5),stores=fixtures(b,readyRows,1),r=resolveProductionBatch(b,readyRows,stores),prompt=batchImagePrompt(b,r);assert.ok(r.posts[0].entries.every(e=>!prompt.includes(e.batchFilename)));assert.ok(r.posts.slice(1).flatMap(p=>p.entries).every(e=>prompt.includes(e.batchFilename)));});

test('kitchen tips preserve practical points; distinct complex states explain any count above target',async()=>{const d=JSON.parse(await readFile(new URL('../data/content-v4-canary.json',import.meta.url)));for(const raw of d.records.filter(r=>r.Content_Type==='KITCHEN_HACK')){const c=normalizeContentRecord(raw),fast=resolveFastVisualPlan(c),count=buildGenerationManifest(fast).entries.length;assert.deepEqual(informationSnapshot(fast),informationSnapshot(c));assert.ok(count>=3);if(count>5){assert.ok(fast.fastVisualPlan.aboveTargetReason);assert.equal(count,buildGenerationManifest(c).entries.length);}else assert.equal(fast.fastVisualPlan.aboveTargetReason,'');assert.equal(runContentQc(fast).failures.length,0);}});
test('an orphan representative-method photo fails structural QC',()=>{const fast=resolveFastVisualPlan(recipe);fast.resolvedAssetPlan.find(a=>a.asset_type==='METHOD').method_steps[0].image_slot_id='missing-image';assert.ok(runContentQc(fast).failures.some(i=>i.code==='METHOD_PHOTO_MAPPING_MISSING'));});

test('temporary source absence preserves the complete batch, reserves and replacement history',async()=>{const {reconcileProductionBatch}=await import('../src/batch-production.mjs');const b=createProductionBatch(readyRows,5),before=JSON.stringify(b),partial=readyRows.filter(r=>r.contentId!==b.posts[0].contentId);const result=reconcileProductionBatch(b,partial);assert.equal(result.changed,false);assert.deepEqual(result.replacements,[]);assert.equal(JSON.stringify(result.batch),before);assert.equal(JSON.stringify(b),before);});
test('legacy partial-source replacement is recovered only if original is eligible and replacement has no media',async()=>{
 const {reconcileProductionBatch}=await import('../src/batch-production.mjs');
 const rows=[...readyRows,row({...readyRows[0].content,contentId:'QA-RECOVERY-RESERVE',title:'QA recovery reserve'},20)],b=createProductionBatch(rows,5),original=b.posts[0],candidate=rows.find(r=>!b.posts.some(p=>p.contentId===r.contentId));assert.ok(candidate);
 const replacement={sheetId:candidate.sheetId,contentId:candidate.contentId,postNumber:1,title:candidate.title,contentType:candidate.contentType,stamp:batchPostStamp(candidate),productionContent:candidate.assessment.productionOverride,replacementGeneration:1},trace={postNumber:1,previousKey:`${original.sheetId}:${original.contentId}`,contentId:original.contentId,replacementKey:`${replacement.sheetId}:${replacement.contentId}`,replacementContentId:replacement.contentId,reason:'CRITICAL_INFO_MISSING'};
 b.posts[0]=replacement;b.replacements=[trace];b.summary.evaluated=rows.length-1;
 const before=JSON.stringify(b),recovered=reconcileProductionBatch(b,rows);assert.equal(recovered.batch.posts[0].contentId,original.contentId);assert.equal(recovered.batch.posts[0].replacementGeneration,0);assert.equal(recovered.batch.replacements[0].restoredAfterSourceRecovery,true);assert.equal(JSON.stringify(b),before);
 const started=reconcileProductionBatch(b,rows,{imagesByKey:new Map([[`${trace.replacementKey}:image:cover`,{}]])});assert.equal(started.batch.posts[0].contentId,replacement.contentId);assert.equal(started.batch.replacements[0].restoredAfterSourceRecovery,undefined);
});

test('manual title batch preserves exact requested order and never pads unrelated content',()=>{
 const available=readyRows.slice(0,3),keys=[`${available[2].sheetId}:${available[2].contentId}`,`${available[0].sheetId}:${available[0].contentId}`],b=createProductionBatchFromSelection(readyRows,keys,7);
 assert.equal(b.selectionMode,'MANUAL');
 assert.equal(b.requestedCount,2);
 assert.equal(b.posts.length,2);
 assert.deepEqual(b.posts.map(p=>`${p.sheetId}:${p.contentId}`),keys);
});
test('manual title batch does not silently replace an explicitly selected post',()=>{
 const available=readyRows.slice(0,3),keys=available.slice(0,2).map(r=>`${r.sheetId}:${r.contentId}`),b=createProductionBatchFromSelection(readyRows,keys,8),first=b.posts[0],changedRows=readyRows.map(r=>r.contentId===first.contentId?{...r,assessment:{...r.assessment,ready:false,recommendation:'SKIP'}}:r),result=reconcileProductionBatch(b,changedRows);
 assert.equal(result.batch.posts[0].contentId,first.contentId);
 assert.deepEqual(result.replacements,[]);
});
test('manual title batch enforces the 20-title interaction limit',()=>{
 const source=readyRows[0],rows=Array.from({length:21},(_,i)=>{const content={...source.content,contentId:`MANUAL-${i}`,title:`Manual ${i}`};return row(content,i);}),keys=rows.map(r=>`${r.sheetId}:${r.contentId}`);
 assert.throws(()=>createProductionBatchFromSelection(rows,keys,9),/at most 20/i);
});
