import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {normalizeContentRecord,buildGenerationManifest,matchGenerationSlot} from '../src/content-model.mjs';
import {assessProduction,optimiseContent,sourceStamp,currentSession,nextProductionAction,canImport,duplicateAssignments} from '../src/production-assistant.mjs';
import {productionGates} from '../src/production-core.mjs';
const [recipes,canary]=await Promise.all(['data/recipes.json','data/v4-production-batch-01.json'].map(async p=>JSON.parse(await readFile(new URL('../'+p,import.meta.url)))));
const recipe=normalizeContentRecord(recipes.recipes.find(r=>r.Content_ID==='EN-NEW-009')||recipes.recipes[0]);
const guide=normalizeContentRecord(canary.records.find(r=>r.Content_ID==='PROD-V4-003'));
const sessionFor=(source,patch)=>({sourceStamp:sourceStamp(source),...patch});
test('low-risk legacy Recipe and V4 guide produce without human approval metadata',()=>{
  for(const source of [recipe,guide]){const content={...source,editorialReview:{},editorialReviewPresent:false};const before=JSON.stringify(content.raw),a=assessProduction(content);assert.equal(a.risk.tier,'LOW');assert.equal(a.recommendation,'PRODUCE',JSON.stringify(a.blockers));assert.equal(a.ready,true);assert.equal(a.humanApproved,false);assert.deepEqual(a.content.editorialReview,{});assert.equal(JSON.stringify(content.raw),before);}
});
test('automatic rewriting preserves quantities, duration, temperature and full factual body',()=>{
  const source={...recipe,title:'你知道吗？家常炒饭',hookText:'太实用了！家常炒饭',caption:'赶快分享！'+recipe.caption};const p=optimiseContent(source);
  assert.doesNotMatch(p.caption,/赶快分享|太实用了|你知道吗/);assert.equal(p.body,recipe.contentBody);assert.ok(p.changes.length);assert.equal(p.content.raw,recipe.raw);assert.equal(p.humanApproved,false);
  const numbers=s=>s.match(/\d+(?:\.\d+)?/g)||[];assert.deepEqual(numbers(p.body),numbers(recipe.contentBody));
});
test('source-backed WHY is optional for a low-risk recipe, never filled with an invented cause',()=>{const source={...recipe,contentBody:'材料按来源准备。先处理食材，再炒至熟透。',caption:'材料和步骤都在图里，煮的时候可以对照。'};const p=optimiseContent(source);assert.equal(p.why,'');assert.doesNotMatch(p.body,/因为|所以/);});
test('medium-risk claim shows verification and high-risk content blocks only that item',()=>{
  for(const [copy,tier] of [['冷藏保存3天','MEDIUM'],['治疗糖尿病','HIGH']]){const source={...recipe,caption:copy};const a=assessProduction(source);assert.equal(a.risk.tier,tier);assert.equal(a.ready,false);assert.equal(a.verified,false);assert.equal(nextProductionAction(a).kind,'CLAIM');assert.match(a.blockers.join(' '),/VERIFY CLAIM/);assert.equal(assessProduction(recipe).ready,true);}
});
test('claim confirmation is specific to the source and is not a human editorial approval',()=>{const source={...recipe,caption:'冷藏保存3天'};const session=sessionFor(source,{claimConfirmation:{sourceStamp:sourceStamp(source),reference:'Checked reference for this exact storage claim'}});const a=assessProduction(source,{session});assert.equal(a.verified,true);assert.equal(a.humanApproved,false);assert.equal(assessProduction({...source,caption:'冷藏保存5天'},{session}).verified,false);});
test('missing essential quantities cannot be auto invented or overridden',()=>{const source={...recipe,schemaVersion:4,raw:{},sourceIngredients:['鸡肉'],resolvedAssetPlan:recipe.resolvedAssetPlan.map(a=>a.asset_type==='INGREDIENTS'?{...a,ingredient_items:[{name:'鸡肉',quantity:''}]}:a)};const a=assessProduction(source,{session:sessionFor(source,{override:'PRODUCE'})});assert.equal(a.ready,false);assert.equal(a.recommendation,'IMPROVE');assert.match(a.gaps.join(' '),/quantities/);assert.equal(nextProductionAction(a).kind,'COMPLETE');});
test('strong duplicate copies skip and cannot be marked Produce',()=>{const a=assessProduction(recipe,{duplicateStatus:'HOLD_DUPLICATE',session:sessionFor(recipe,{override:'PRODUCE'})});assert.equal(a.recommendation,'SKIP');assert.equal(a.ready,false);assert.equal(nextProductionAction(a).kind,'CANONICAL');});
test('PRODUCE / IMPROVE / SKIP overrides remain lightweight but respect factual gates',()=>{for(const recommendation of ['PRODUCE','IMPROVE','SKIP']){const a=assessProduction(recipe,{session:sessionFor(recipe,{override:recommendation})});assert.equal(a.recommendation,recommendation);assert.equal(a.ready,recommendation==='PRODUCE');}});
test('AI-fixable generic copy improves automatically before requesting manual input',()=>{const source={...recipe,caption:'你知道吗？太实用了！'};const before=assessProduction(source,{optimised:false}),after=assessProduction(source);assert.equal(before.recommendation,'IMPROVE');assert.equal(after.recommendation,'PRODUCE');assert.ok(after.proposal.caption.length>30);assert.equal(after.gaps.length,0);});
test('resume source stamp preserves iterations and override only for the current source',()=>{const saved=sessionFor(recipe,{iteration:2,override:'SKIP',downloadedAt:'2026-10-04'});assert.equal(currentSession(recipe,saved),saved);assert.equal(currentSession({...recipe,contentBody:recipe.contentBody+'Changed'},saved).override,undefined);});
test('action progression: Content to Images to Final to Download and no visual gate on import',()=>{const a=assessProduction(guide),manifest=buildGenerationManifest(a.content),plan=a.content.resolvedAssetPlan;assert.equal(canImport(a),true);assert.equal(nextProductionAction(a,{manifest,plan}).kind,'IMAGES');const images=Object.fromEntries(manifest.entries.map(e=>[e.slotId,{semanticKey:e.semanticKey,qc:{status:'PASS'}}]));assert.equal(nextProductionAction(a,{manifest,images,plan}).kind,'BUILD');const assets=Object.fromEntries(plan.map(p=>[p.asset_id,{qc_status:'PASS',stale:false}]));assert.equal(nextProductionAction(a,{manifest,images,plan,assets}).kind,'FINAL');assert.equal(nextProductionAction(a,{manifest,images,plan,assets,visualReviewed:true}).kind,'DOWNLOAD');assets[plan[0].asset_id].stale=true;assert.equal(nextProductionAction(a,{manifest,images,plan,assets,visualReviewed:true}).kind,'BUILD');});
test('export accepts automatic low-risk production checks but fails on stale assets or missing visual decision',()=>{const a=assessProduction(guide),manifest=buildGenerationManifest(a.content),plan=a.content.resolvedAssetPlan,images=Object.fromEntries(manifest.entries.map(e=>[e.slotId,{semanticKey:e.semanticKey,qc:{status:'PASS'}}])),assets=Object.fromEntries(plan.map(p=>[p.asset_id,{qc_status:'PASS',stale:false}]));const context={contract:a.contract,editorial:{status:'NOT_REVIEWED'},productionDecision:a,generation:{ready:a.ready},manifest,plan,images,assets,visualReviewed:true};assert.equal(productionGates(context).exportReady,true);assert.equal(productionGates({...context,visualReviewed:false}).exportReady,false);assets[plan[0].asset_id].stale=true;assert.equal(productionGates(context).exportReady,false);});
test('primary review DOM and obsolete handlers are removed while historical API remains compatible',async()=>{const [html,app]=await Promise.all(['public/index.html','public/app.js'].map(p=>readFile(new URL('../'+p,import.meta.url),'utf8')));assert.doesNotMatch(html,/id="(?:workReviewer|editorReviewer|workApprove|saveEditorialReview|workConsistency)"/);assert.doesNotMatch(app,/function (?:saveEditorialWork|editorialReviewPayload|saveEditorialReview)\(/);assert.match(html,/id="primaryAction"/);assert.match(html,/id="looksGood"/);});

test('production canonical group format holds copies even without a precomputed assignments field',()=>{const map={groups:[{canonical:{sheetId:1,contentId:'A'},duplicates:[{sheetId:2,contentId:'B'}]}]};assert.deepEqual(duplicateAssignments(map)['2:B'],{status:'HOLD_DUPLICATE',canonicalKey:'1:A'});});

test('download names with explicit image sequence map without renaming and contradictory sequences refuse mapping',()=>{const manifest=buildGenerationManifest(recipe);assert.equal(matchGenerationSlot('ChatGPT Image 04 download.png',manifest),manifest.entries[3].slotId);assert.equal(matchGenerationSlot('ChatGPT Image 04 Image 05.png',manifest),null);assert.equal(matchGenerationSlot('ChatGPT Image 04 COVER.png',manifest),null);});

test('Chinese storage durations and disease prevention are meaningful claims rather than automatic low risk',()=>{assert.equal(assessProduction({...recipe,caption:'煮好以后冷藏保存三天。'}).risk.tier,'MEDIUM');assert.equal(assessProduction({...recipe,caption:'这个食谱可以预防感冒。'}).risk.tier,'HIGH');});
