import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {normalizeContentRecord} from '../src/content-model.mjs';
import {assessProduction,sourceStamp,changeToken,buildContentCompletionPrompt,nextProductionAction} from '../src/production-assistant.mjs';
import {createProductionBatch,reconcileProductionBatch,resolveProductionBatch,screenProductionRows} from '../src/batch-production.mjs';
const source=normalizeContentRecord(JSON.parse(await readFile(new URL('./fixtures/auto-repair/GS-V4-EXP-047.json',import.meta.url))));
// Explicit test additions only, never claimed to be a verified recipe or a source-Sheet correction.
export const draft='食材\n猪肉500g；蜂蜜20g；生抽20ml\n做法\n1. 猪肉切成条，加入生抽拌匀。\n2. 放入锅内煎，翻面煎至猪肉熟透。\n3. 加入蜂蜜拌匀收汁。';
const session=(s,text=draft)=>({sourceStamp:sourceStamp(s),completion:{text,sourceStamp:sourceStamp(s),inputStamp:changeToken(JSON.stringify(s.raw)),provenance:'USER_PROVIDED_PRODUCTION_ADDITIONS'}});
test('incomplete actual record has same-content continuation and no invented recipe',()=>{const a=assessProduction(source);assert.equal(a.recommendation,'IMPROVE');assert.equal(a.preparation.continuation,'COMPLETE_THIS_CONTENT');assert.equal(nextProductionAction(a).kind,'COMPLETE');assert.equal(a.ready,false);assert.equal(a.manifest.entries.length,0);assert.doesNotMatch(a.content.contentBody,/500g|20g|20ml/);const p=buildContentCompletionPrompt(source,a);assert.match(p,/KEEP CONTENT ID: GS-V4-EXP-047/);assert.match(p,/ask only for that fact/);assert.match(p,/Never silently invent quantities/);});
test('explicit production additions complete the same record without changing the original or claiming approval',()=>{const before=JSON.stringify(source),a=assessProduction(source,{session:session(source)});assert.equal(a.ready,true,JSON.stringify(a.blockers));assert.equal(a.content.contentId,source.contentId);assert.equal(a.content.raw,source.raw);assert.equal(JSON.stringify(source),before);assert.equal(a.humanApproved,false);assert.equal(a.productionOverride.humanApproved,false);assert.ok(a.factConfidence.some(c=>c.confidence==='USER PROVIDED'));assert.ok(a.manifest.entries.every(e=>e.imagePrompt.includes('猪肉500g')));assert.ok(a.manifest.entries.length>0);assert.match(nextProductionAction(a,{manifest:a.manifest}).label,/Generate Images/);});
test('partial additions save useful progress but do not waive remaining factual gaps',()=>{const a=assessProduction(source,{session:session(source,'食材\n猪肉；蜂蜜；生抽\n做法\n1. 猪肉切条。\n2. 放入锅内煎至熟透。')});assert.equal(a.ready,false);assert.equal(a.recommendation,'IMPROVE');assert.equal(a.manifest.entries.length,0);assert.doesNotMatch(a.content.contentBody,/500g|20g|20ml/);});
test('persisted additions survive serialization only for the same source stamp and raw input',()=>{const saved=JSON.parse(JSON.stringify(session(source)));assert.equal(assessProduction(source,{session:saved}).ready,true);for(const changed of [{...source,contentBody:source.contentBody+'\n来源变更'},{...source,raw:{...source.raw,Source_Revision:'NEW'}}]){const a=assessProduction(changed,{session:saved});assert.equal(a.ready,false);assert.doesNotMatch(a.content.contentBody,/500g/);}});
test('production additions cannot erase unsupported health claims from the original record',()=>{const s={...source,caption:'治疗糖尿病，保证有效。'};const a=assessProduction(s,{session:session(s)});assert.equal(a.risk.tier,'HIGH');assert.equal(a.ready,false);assert.match(a.content.caption,/糖尿病/);assert.equal(a.manifest.entries.length,0);});
test('a kept batch post resumes on the same ID and ordinal after completion; other posts stay valid',()=>{const fixed={...source,contentId:'KEEP-ME'},rows=Array.from({length:7},(_,i)=>{const c={...source,contentId:i===0?'KEEP-ME':`ZZ-GOOD-${i}`};return {sheetId:1,contentId:c.contentId,content:c,title:c.title,contentType:'RECIPE',duplicateStatus:'UNIQUE',session:session(c),assessment:assessProduction(c,{session:session(c)})};});const b=createProductionBatch(rows,5),index=b.posts.findIndex(p=>p.contentId==='KEEP-ME');assert.ok(index>=0);const broken=rows.map(r=>r.contentId==='KEEP-ME'?{...r,session:{},assessment:assessProduction(fixed)}:r),kept=reconcileProductionBatch(b,broken);assert.equal(kept.replacements.length,0);assert.equal(kept.batch.posts[index].contentId,'KEEP-ME');assert.match(resolveProductionBatch(kept.batch,broken).posts[index].status,/COMPLETE THIS CONTENT/);const completed=screenProductionRows(rows),resumed=reconcileProductionBatch(kept.batch,completed),p=resolveProductionBatch(resumed.batch,completed).posts[index];assert.equal(p.valid,true);assert.equal(p.contentId,'KEEP-ME');assert.equal(p.postNumber,b.posts[index].postNumber);assert.equal(p.replacementGeneration,undefined);});

test('completion method is recovered independently of a partially filled legacy recipe',()=>{const s={...source,raw:{...source.raw,Full_Recipe:'食材\n猪肉；蜂蜜；生抽\n做法\n1. 猪肉切条。'}};const a=assessProduction(s,{session:session(s)});assert.equal(a.ready,true,JSON.stringify(a.blockers));assert.ok(a.repair.evidence.some(e=>e.path==='raw.Production_Completion'));assert.equal(a.content.raw.Full_Recipe,s.raw.Full_Recipe);});

test('one explicit missing ingredient quantity is enough; no full recipe rewrite required',async()=>{const raw=JSON.parse(await readFile(new URL('../data/recipes.json',import.meta.url))),s=normalizeContentRecord(raw.recipes.find(r=>r.Content_ID==='EN-NEW-009'));const ready=assessProduction(s).content,ingredient=ready.resolvedAssetPlan.find(a=>a.asset_type==='INGREDIENTS');const target=ingredient.ingredient_items[0];const clean={...source,title:s.title,hookText:s.hookText,contentBody:'家常焖饭',caption:'家常焖饭',sourceIngredients:ingredient.ingredient_items.map(i=>i.name),coveragePoints:ready.coveragePoints,raw:{},resolvedAssetPlan:structuredClone(ready.resolvedAssetPlan)};const list=clean.resolvedAssetPlan.find(a=>a.asset_type==='INGREDIENTS');list.ingredient_items[0].quantity='';list.generation_inputs.forEach(i=>i.image_prompt='Source ingredients');list.overlay_text='';const a=assessProduction(clean,{session:session(clean,target.name+' '+target.quantity)});assert.equal(a.ready,true,JSON.stringify(a.blockers));assert.ok(a.repair.autoFixed.some(i=>i.code==='INGREDIENTS_RECOVERED'));});
